import App from "next/app"
import "../styles/globals.css";
import Head from "next/head";
import { createContext } from "react";
import { fetchAPI } from "../lib/api";
import { getStrapiMedia } from "../lib/media";

export const GlobalContext = createContext({});

function MyApp({ Component, pageProps }) {
  const { global } = pageProps;

  return (
    <>
      <Head>
        <title>No Problems Fitness</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="true"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Amaranth&family=Cambay&family=Montserrat&display=swap"
          rel="stylesheet"
        />
      </Head>
      <GlobalContext.Provider >
        <Component {...pageProps} />
      </GlobalContext.Provider>
    </>
  );
}


export default MyApp;
