import Head from 'next/head'
import Header from '../components/Header'
import Image from 'next/image'
import LargeGrid from '../components/LargeGrid'
import PostsGrid from '../components/PostsGrid'


export default function Home() {
  return (
    <main>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <LargeGrid />
      <section>
      <PostsGrid />
        <PostsGrid />
        <PostsGrid />
        <PostsGrid />
        <PostsGrid />
        <PostsGrid />
        <PostsGrid />
        </section>
      <style jsx>{`
      @media(min-width:1280px){
        main {
          margin: 0 100px;
        }
          section{
            margin: 0 100px;
            display:grid;
            gap: 50px;
            grid-template-columns: 1fr 1fr 1fr;
          }
      }
      `}</style>
    </main>
  )
}
